
BaseDesignations:
	db " Nidoran ",$81
	db " Nidoran ",$80
	db "  Slowpoke"
	db "Kangaskhan"
	db "   Rhyhorn"
	db "    Grimer"
	db "   Voltorb"
	db "    Gengar"
	db "   Marowak"
	db "  Nidoking"
	db " Nidoqueen"
	db " Exeggcute"
	db " Lickitung"
	db "Exeggcutor"
	db " Poliwrath"
	db "  Venusaur"
	db "   Spearow"
	db "    Rhydon"
	db "   Tangela"
	db " Blastoise"
	db "    Pinsir"
	db "  Arcanine"
	db "   Scyther"
	db "  Gyarados"
	db "  Shellder"
	db "    Cubone"
	db " Tentacool"
	db "    Lapras"
	db "    Gastly"
	db "    Crobat"
	db "   Starmie"
	db "   Slowbro"
	db "  Mr. Mime"
	db "   Psyduck"
	db "   Rattata"
	db "Aerodactyl"
	db "  Graveler"
	db "    Ponyta"

	db "   Murkrow"
	db "  Spinarak"
	db "    Togepi"
	db " Girafarig"
	db " Tyranitar"
	db "   Flaaffy"
	db "   Togetic"
	db "  Hoothoot"
	db "    Phanpy"
	db "  Slowking"
	db "  Houndour"
	db " Chikorita"
	db " Octillery"
	db "   Miltank"
	db "  Jumpluff"
	db " Hitmontop"
	db "    Ledyba"
	db "     Entei"
	db "   Sneasel"
	db "   Mantine"
	db "     Lugia"
	db "      Xatu"
	db "  Delibird"
	db "  Remoraid"
	db "    Scizor"
	db "   Suicune"
	db "     Pichu"
	db "     Ho-oh"
	db "  Granbull"
	db "   Donphan"
