MACRO mon_cry
; index, pitch, length
	dw \1
	db \2
	db $80 ^ \3
ENDM

PokemonCries::
; entries correspond to constants/pokemon_constants.asm
	mon_cry CRY_BULBASAUR,   $80,  $81 ; BULBASAUR
	mon_cry CRY_BULBASAUR,   $20,  $00 ; IVYSAUR
	mon_cry CRY_BULBASAUR,   $00,  $40 ; VENUSAUR
	mon_cry CRY_CHARMANDER,  $60,  $c0 ; CHARMANDER
	mon_cry CRY_CHARMANDER,  $20,  $c0 ; CHARMELEON
	mon_cry CRY_CHARMANDER,  $00,  $00 ; CHARIZARD
	mon_cry CRY_SQUIRTLE,    $60,  $c0 ; SQUIRTLE
	mon_cry CRY_SQUIRTLE,    $20,  $c0 ; WARTORTLE
	mon_cry CRY_BLASTOISE,   $00,  $00 ; BLASTOISE
	mon_cry CRY_CATERPIE,    $80,  $a0 ; CATERPIE
	mon_cry CRY_METAPOD,     $cc,  $81 ; METAPOD
	mon_cry CRY_CATERPIE,    $77,  $c0 ; BUTTERFREE
	mon_cry CRY_WEEDLE,      $ee,  $81 ; WEEDLE
	mon_cry CRY_BLASTOISE,   $ff,  $81 ; KAKUNA
	mon_cry CRY_BLASTOISE,   $60,  $00 ; BEEDRILL
	mon_cry CRY_PIDGEY,      $df,  $84 ; PIDGEY
	mon_cry CRY_PIDGEOTTO,   $28,  $40 ; PIDGEOTTO
	mon_cry CRY_PIDGEOTTO,   $11,  $7f ; PIDGEOT
	mon_cry CRY_RATTATA,     $00,  $00 ; RATTATA
	mon_cry CRY_RATTATA,     $20,  $7f ; RATICATE
	mon_cry CRY_SPEAROW,     $00,  $00 ; SPEAROW
	mon_cry CRY_FEAROW,      $40,  $20 ; FEAROW
	mon_cry CRY_EKANS,       $12,  $c0 ; EKANS
	mon_cry CRY_EKANS,       $e0,  $90 ; ARBOK
	mon_cry CRY_BULBASAUR,   $ee,  $81 ; PIKACHU
	mon_cry CRY_RAICHU,      $ee,  $88 ; RAICHU
	mon_cry CRY_NIDORAN_M,   $20,  $c0 ; SANDSHREW
	mon_cry CRY_NIDORAN_M,   $ff,  $7f ; SANDSLASH
	mon_cry CRY_NIDORAN_F,   $00,  $00 ; NIDORAN_F
	mon_cry CRY_NIDORAN_F,   $2c,  $60 ; NIDORINA
	mon_cry CRY_NIDOQUEEN,   $00,  $00 ; NIDOQUEEN
	mon_cry CRY_NIDORAN_M,   $00,  $00 ; NIDORAN_M
	mon_cry CRY_NIDORAN_M,   $2c,  $40 ; NIDORINO
	mon_cry CRY_RAICHU,      $00,  $00 ; NIDOKING
	mon_cry CRY_CLEFAIRY,    $cc,  $81 ; CLEFAIRY
	mon_cry CRY_CLEFAIRY,    $aa,  $a0 ; CLEFABLE
	mon_cry CRY_VULPIX,      $4f,  $90 ; VULPIX
	mon_cry CRY_VULPIX,      $88,  $e0 ; NINETALES
	mon_cry CRY_PIDGEY,      $ff,  $b5 ; JIGGLYPUFF
	mon_cry CRY_PIDGEY,      $68,  $e0 ; WIGGLYTUFF
	mon_cry CRY_SQUIRTLE,    $e0,  $00 ; ZUBAT
	mon_cry CRY_SQUIRTLE,    $fa,  $00 ; GOLBAT
	mon_cry CRY_ODDISH,      $dd,  $81 ; ODDISH
	mon_cry CRY_ODDISH,      $aa,  $c0 ; GLOOM
	mon_cry CRY_VILEPLUME,   $22,  $7f ; VILEPLUME
	mon_cry CRY_PARAS,       $20,  $60 ; PARAS
	mon_cry CRY_PARAS,       $42,  $7f ; PARASECT
	mon_cry CRY_VENONAT,     $44,  $c0 ; VENONAT
	mon_cry CRY_VENONAT,     $29,  $00 ; VENOMOTH
	mon_cry CRY_DIGLETT,     $aa,  $81 ; DIGLETT
	mon_cry CRY_DIGLETT,     $2a,  $90 ; DUGTRIO
	mon_cry CRY_CLEFAIRY,    $77,  $90 ; MEOWTH
	mon_cry CRY_CLEFAIRY,    $99,  $7f ; PERSIAN
	mon_cry CRY_PSYDUCK,     $20,  $e0 ; PSYDUCK
	mon_cry CRY_PSYDUCK,     $ff,  $c0 ; GOLDUCK
	mon_cry CRY_NIDOQUEEN,   $dd,  $e0 ; MANKEY
	mon_cry CRY_NIDOQUEEN,   $af,  $c0 ; PRIMEAPE
	mon_cry CRY_GROWLITHE,   $20,  $c0 ; GROWLITHE
	mon_cry CRY_WEEDLE,      $00,  $00 ; ARCANINE
	mon_cry CRY_PIDGEY,      $ff,  $7f ; POLIWAG
	mon_cry CRY_PIDGEY,      $77,  $e0 ; POLIWHIRL
	mon_cry CRY_PIDGEY,      $00,  $7f ; POLIWRATH
	mon_cry CRY_METAPOD,     $c0,  $81 ; ABRA
	mon_cry CRY_METAPOD,     $a8,  $40 ; KADABRA
	mon_cry CRY_METAPOD,     $98,  $7f ; ALAKAZAM
	mon_cry CRY_GROWLITHE,   $ee,  $81 ; MACHOP
	mon_cry CRY_GROWLITHE,   $48,  $e0 ; MACHOKE
	mon_cry CRY_GROWLITHE,   $08,  $40 ; MACHAMP
	mon_cry CRY_PSYDUCK,     $55,  $81 ; BELLSPROUT
	mon_cry CRY_WEEPINBELL,  $44,  $a0 ; WEEPINBELL
	mon_cry CRY_WEEPINBELL,  $66,  $4c ; VICTREEBEL
	mon_cry CRY_VENONAT,     $00,  $00 ; TENTACOOL
	mon_cry CRY_VENONAT,     $ee,  $7f ; TENTACRUEL
	mon_cry CRY_VULPIX,      $f0,  $90 ; GEODUDE
	mon_cry CRY_VULPIX,      $00,  $00 ; GRAVELER
	mon_cry CRY_GOLEM,       $e0,  $c0 ; GOLEM
	mon_cry CRY_WEEPINBELL,  $00,  $00 ; PONYTA
	mon_cry CRY_WEEPINBELL,  $20,  $40 ; RAPIDASH
	mon_cry CRY_SLOWPOKE,    $00,  $00 ; SLOWPOKE
	mon_cry CRY_GROWLITHE,   $00,  $00 ; SLOWBRO
	mon_cry CRY_METAPOD,     $80,  $e0 ; MAGNEMITE
	mon_cry CRY_METAPOD,     $20,  $40 ; MAGNETON
	mon_cry CRY_SPEAROW,     $dd,  $81 ; FARFETCH_D
	mon_cry CRY_DIGLETT,     $bb,  $81 ; DODUO
	mon_cry CRY_DIGLETT,     $99,  $a0 ; DODRIO
	mon_cry CRY_SEEL,        $88,  $40 ; SEEL
	mon_cry CRY_SEEL,        $23,  $7f ; DEWGONG
	mon_cry CRY_GRIMER,      $00,  $00 ; GRIMER
	mon_cry CRY_MUK,         $ef,  $7f ; MUK
	mon_cry CRY_FEAROW,      $00,  $00 ; SHELLDER
	mon_cry CRY_FEAROW,      $6f,  $60 ; CLOYSTER
	mon_cry CRY_METAPOD,     $00,  $00 ; GASTLY
	mon_cry CRY_METAPOD,     $30,  $c0 ; HAUNTER
	mon_cry CRY_MUK,         $00,  $7f ; GENGAR
	mon_cry CRY_EKANS,       $ff,  $40 ; ONIX
	mon_cry CRY_DROWZEE,     $88,  $a0 ; DROWZEE
	mon_cry CRY_DROWZEE,     $ee,  $c0 ; HYPNO
	mon_cry CRY_KRABBY,      $20,  $60 ; KRABBY
	mon_cry CRY_KRABBY,      $ee,  $60 ; KINGLER
	mon_cry CRY_VOLTORB,     $ed,  $00 ; VOLTORB
	mon_cry CRY_VOLTORB,     $a8,  $10 ; ELECTRODE
	mon_cry CRY_DIGLETT,     $00,  $00 ; EXEGGCUTE
	mon_cry CRY_DROWZEE,     $00,  $00 ; EXEGGUTOR
	mon_cry CRY_CLEFAIRY,    $00,  $00 ; CUBONE
	mon_cry CRY_ODDISH,      $4f,  $e0 ; MAROWAK
	mon_cry CRY_GOLEM,       $80,  $40 ; HITMONLEE
	mon_cry CRY_SEEL,        $ee,  $40 ; HITMONCHAN
	mon_cry CRY_SEEL,        $00,  $00 ; LICKITUNG
	mon_cry CRY_GOLEM,       $e6,  $5d ; KOFFING
	mon_cry CRY_GOLEM,       $ff,  $7f ; WEEZING
	mon_cry CRY_CHARMANDER,  $00,  $00 ; RHYHORN
	mon_cry CRY_RHYDON,      $00,  $00 ; RHYDON
	mon_cry CRY_PIDGEOTTO,   $0a,  $40 ; CHANSEY
	mon_cry CRY_GOLEM,       $00,  $00 ; TANGELA
	mon_cry CRY_KANGASKHAN,  $00,  $00 ; KANGASKHAN
	mon_cry CRY_CLEFAIRY,    $99,  $90 ; HORSEA
	mon_cry CRY_CLEFAIRY,    $3c,  $81 ; SEADRA
	mon_cry CRY_CATERPIE,    $80,  $c0 ; GOLDEEN
	mon_cry CRY_CATERPIE,    $10,  $7f ; SEAKING
	mon_cry CRY_PARAS,       $02,  $a0 ; STARYU
	mon_cry CRY_PARAS,       $00,  $00 ; STARMIE
	mon_cry CRY_KRABBY,      $08,  $c0 ; MR__MIME
	mon_cry CRY_CATERPIE,    $00,  $00 ; SCYTHER
	mon_cry CRY_DROWZEE,     $ff,  $7f ; JYNX
	mon_cry CRY_VOLTORB,     $8f,  $7f ; ELECTABUZZ
	mon_cry CRY_CHARMANDER,  $ff,  $b0 ; MAGMAR
	mon_cry CRY_PIDGEOTTO,   $00,  $00 ; PINSIR
	mon_cry CRY_SQUIRTLE,    $11,  $c0 ; TAUROS
	mon_cry CRY_EKANS,       $80,  $80 ; MAGIKARP
	mon_cry CRY_EKANS,       $00,  $00 ; GYARADOS
	mon_cry CRY_LAPRAS,      $00,  $00 ; LAPRAS
	mon_cry CRY_PIDGEY,      $ff,  $7f ; DITTO
	mon_cry CRY_VENONAT,     $88,  $e0 ; EEVEE
	mon_cry CRY_VENONAT,     $aa,  $7f ; VAPOREON
	mon_cry CRY_VENONAT,     $3d,  $00 ; JOLTEON
	mon_cry CRY_VENONAT,     $10,  $a0 ; FLAREON
	mon_cry CRY_WEEPINBELL,  $aa,  $7f ; PORYGON
	mon_cry CRY_GROWLITHE,   $f0,  $81 ; OMANYTE
	mon_cry CRY_GROWLITHE,   $ff,  $c0 ; OMASTAR
	mon_cry CRY_CATERPIE,    $bb,  $c0 ; KABUTO
	mon_cry CRY_FEAROW,      $ee,  $81 ; KABUTOPS
	mon_cry CRY_VILEPLUME,   $20,  $70 ; AERODACTYL
	mon_cry CRY_GRIMER,      $55,  $81 ; SNORLAX
	mon_cry CRY_RAICHU,      $80,  $c0 ; ARTICUNO
	mon_cry CRY_FEAROW,      $ff,  $00 ; ZAPDOS
	mon_cry CRY_RAICHU,      $f8,  $c0 ; MOLTRES
	mon_cry CRY_BULBASAUR,   $60,  $c0 ; DRATINI
	mon_cry CRY_BULBASAUR,   $40,  $00 ; DRAGONAIR
	mon_cry CRY_BULBASAUR,   $3c,  $40 ; DRAGONITE
	mon_cry CRY_PARAS,       $99,  $7f ; MEWTWO
	mon_cry CRY_PARAS,       $ee,  $7f ; MEW

	mon_cry CRY_CHIKORITA,   $20,  $b0 ; CHIKORITA
	mon_cry CRY_CHIKORITA,   $10,  $20 ; BAYLEEF
	mon_cry CRY_CHIKORITA,   $00,  $7f ; MEGANIUM
	mon_cry CRY_CYNDAQUIL,   $47,  $80 ; CYNDAQUIL
	mon_cry CRY_CYNDAQUIL,   $21,  $20 ; QUILAVA
	mon_cry CRY_TYPHLOSION,  $c0,  $d4 ; TYPHLOSION
	mon_cry CRY_CHARMANDER,  $f0,  $d4 ; TOTODILE
	mon_cry CRY_CHARMANDER,  $e0,  $f4 ; CROCONAW
	mon_cry CRY_CHARMANDER,  $b1,  $34 ; FERALIGATR
	mon_cry CRY_SENTRET,     $8a,  $b8 ; SENTRET
	mon_cry CRY_SENTRET,     $6b,  $02 ; FURRET
	mon_cry CRY_HOOTHOOT,    $91,  $d8 ; HOOTHOOT
	mon_cry CRY_HOOTHOOT,    $00,  $7f ; NOCTOWL
	mon_cry CRY_LEDYBA,      $08,  $de ; LEDYBA
	mon_cry CRY_LEDYBA,      $00,  $38 ; LEDIAN
	mon_cry CRY_SPINARAK,    $11,  $7f ; SPINARAK
	mon_cry CRY_SPINARAK,    $00,  $71 ; ARIADOS
	mon_cry CRY_SQUIRTLE,    $00,  $40 ; CROBAT
	mon_cry CRY_CYNDAQUIL,   $c9,  $40 ; CHINCHOU
	mon_cry CRY_CYNDAQUIL,   $18,  $10 ; LANTURN
	mon_cry CRY_PICHU,       $00,  $22 ; PICHU
	mon_cry CRY_CLEFFA,      $61,  $ba ; CLEFFA
	mon_cry CRY_CHIKORITA,   $30,  $e8 ; IGGLYBUFF
	mon_cry CRY_TOGEPI,      $10,  $00 ; TOGEPI
	mon_cry CRY_TOGETIC,     $00,  $80 ; TOGETIC
	mon_cry CRY_NATU,        $40,  $00 ; NATU
	mon_cry CRY_NATU,        $00,  $68 ; XATU
	mon_cry CRY_MAREEP,      $22,  $d8 ; MAREEP
	mon_cry CRY_MAREEP,      $00,  $7f ; FLAAFFY
	mon_cry CRY_FEAROW,      $10,  $1f ; AMPHAROS
	mon_cry CRY_CLEFFA,      $84,  $33 ; BELLOSSOM
	mon_cry CRY_MARILL,      $f0,  $20 ; MARILL
	mon_cry CRY_MARILL,      $b6,  $7f ; AZUMARILL
	mon_cry CRY_CLEFFA,      $10,  $51 ; SUDOWOODO
	mon_cry CRY_EKANS,       $40,  $1f ; POLITOED
	mon_cry CRY_CLEFFA,      $3b,  $dc ; HOPPIP
	mon_cry CRY_CLEFFA,      $27,  $24 ; SKIPLOOM
	mon_cry CRY_CLEFFA,      $00,  $51 ; JUMPLUFF
	mon_cry CRY_AIPOM,       $10,  $e8 ; AIPOM
	mon_cry CRY_MARILL,      $ff,  $b8 ; SUNKERN
	mon_cry CRY_SUNFLORA,    $d2,  $7f ; SUNFLORA
	mon_cry CRY_TOTODILE,    $31,  $c8 ; YANMA
	mon_cry CRY_WOOPER,      $93,  $af ; WOOPER
	mon_cry CRY_WOOPER,      $00,  $40 ; QUAGSIRE
	mon_cry CRY_AIPOM,       $a2,  $40 ; ESPEON
	mon_cry CRY_BLASTOISE,   $9c,  $cd ; UMBREON
	mon_cry CRY_MARILL,      $00,  $7f ; MURKROW
	mon_cry CRY_SLOWKING,    $ff,  $7f ; SLOWKING
	mon_cry CRY_HOOTHOOT,    $cf,  $e8 ; MISDREAVUS
	mon_cry CRY_HOOTHOOT,    $ff,  $00 ; UNOWN
	mon_cry CRY_AMPHAROS,    $5f,  $44 ; WOBBUFFET
	mon_cry CRY_GIRAFARIG,   $41,  $66 ; GIRAFARIG
	mon_cry CRY_SLOWKING,    $80,  $00 ; PINECO
	mon_cry CRY_SLOWKING,    $00,  $7f ; FORRETRESS
	mon_cry CRY_DUNSPARCE,   $b0,  $00 ; DUNSPARCE
	mon_cry CRY_GLIGAR,      $fe,  $00 ; GLIGAR
	mon_cry CRY_TYPHLOSION,  $ef,  $f7 ; STEELIX
	mon_cry CRY_DUNSPARCE,   $6b,  $e8 ; SNUBBULL
	mon_cry CRY_DUNSPARCE,   $00,  $7f ; GRANBULL
	mon_cry CRY_SLOWKING,    $60,  $e0 ; QWILFISH
	mon_cry CRY_AMPHAROS,    $00,  $60 ; SCIZOR
	mon_cry CRY_DUNSPARCE,   $ff,  $a8 ; SHUCKLE
	mon_cry CRY_AMPHAROS,    $35,  $e0 ; HERACROSS
	mon_cry CRY_WOOPER,      $53,  $af ; SNEASEL
	mon_cry CRY_TEDDIURSA,   $00,  $80 ; TEDDIURSA
	mon_cry CRY_TEDDIURSA,   $ff,  $d8 ; URSARING
	mon_cry CRY_EKANS,       $df,  $40 ; SLUGMA
	mon_cry CRY_PSYDUCK,     $5f,  $1f ; MAGCARGO
	mon_cry CRY_CYNDAQUIL,   $00,  $40 ; SWINUB
	mon_cry CRY_GRIMER,      $c0,  $e0 ; PILOSWINE
	mon_cry CRY_MAGCARGO,    $a1,  $e8 ; CORSOLA
	mon_cry CRY_SUNFLORA,    $ff,  $00 ; REMORAID
	mon_cry CRY_TOTODILE,    $00,  $7f ; OCTILLERY
	mon_cry CRY_TEDDIURSA,   $08,  $80 ; DELIBIRD
	mon_cry CRY_MANTINE,     $00,  $f0 ; MANTINE
	mon_cry CRY_AMPHAROS,    $a9,  $7f ; SKARMORY
	mon_cry CRY_CYNDAQUIL,   $ff,  $40 ; HOUNDOUR
	mon_cry CRY_TOTODILE,    $0a,  $00 ; HOUNDOOM
	mon_cry CRY_SLUGMA,      $ff,  $00 ; KINGDRA
	mon_cry CRY_SENTRET,     $48,  $80 ; PHANPY
	mon_cry CRY_DONPHAN,     $00,  $7f ; DONPHAN
	mon_cry CRY_GIRAFARIG,   $73,  $67 ; PORYGON2
	mon_cry CRY_EKANS,       $f4,  $7f ; STANTLER
	mon_cry CRY_SLOWPOKE,    $20,  $7f ; SMEARGLE
	mon_cry CRY_AIPOM,       $2c,  $08 ; TYROGUE
	mon_cry CRY_SLUGMA,      $00,  $00 ; HITMONTOP
	mon_cry CRY_MARILL,      $68,  $00 ; SMOOCHUM
	mon_cry CRY_SUNFLORA,    $00,  $b4 ; ELEKID
	mon_cry CRY_TEDDIURSA,   $20,  $80 ; MAGBY
	mon_cry CRY_GLIGAR,      $33,  $7f ; MILTANK
	mon_cry CRY_MARILL,      $80,  $7f ; BLISSEY
	mon_cry CRY_ENTEI,       $a4,  $df ; RAIKOU
	mon_cry CRY_ENTEI,       $00,  $7f ; ENTEI
	mon_cry CRY_MAGCARGO,    $00,  $7f ; SUICUNE
	mon_cry CRY_RAIKOU,      $5f,  $d0 ; LARVITAR
	mon_cry CRY_SPINARAK,    $ff,  $28 ; PUPITAR
	mon_cry CRY_RAIKOU,      $00,  $7f ; TYRANITAR
	mon_cry CRY_TYPHLOSION,  $00,  $00 ; LUGIA
	mon_cry CRY_AIPOM,       $00,  $7f ; HO_OH
	mon_cry CRY_ENTEI,       $ff,  $11 ; CELEBI
	mon_cry CRY_NIDORAN_M,   $80,  $80
	mon_cry CRY_NIDORAN_M,   $80,  $80
	mon_cry CRY_NIDORAN_M,   $80,  $80
	mon_cry CRY_NIDORAN_M,   $80,  $80
	mon_cry CRY_NIDORAN_M,   $80,  $80
