; What music plays when a trainer notices you

TrainerEncounterMusic::
; entries correspond to trainer classes (see constants/trainer_constants.asm)
	table_width 1, TrainerEncounterMusic
	db MUSIC_BAD_GUY_ENCOUNTER     ; none
	db MUSIC_BOY_ENCOUNTER         ; falkner
	db MUSIC_GIRL_ENCOUNTER        ; whitney
	db MUSIC_BOY_ENCOUNTER         ; bugsy
	db MUSIC_BOY_ENCOUNTER         ; morty
	db MUSIC_BOY_ENCOUNTER         ; pryce
	db MUSIC_GIRL_ENCOUNTER        ; jasmine
	db MUSIC_BOY_ENCOUNTER         ; chuck
	db MUSIC_GIRL_ENCOUNTER        ; clair
	db MUSIC_RIVAL_ENCOUNTER       ; rival1
	db MUSIC_BAD_GUY_ENCOUNTER     ; pokemon_prof
	db MUSIC_BAD_GUY_ENCOUNTER     ; will
	db MUSIC_BAD_GUY_ENCOUNTER     ; cal
	db MUSIC_BOY_ENCOUNTER         ; bruno
	db MUSIC_BAD_GUY_ENCOUNTER     ; karen
	db MUSIC_BAD_GUY_ENCOUNTER     ; koga
	db MUSIC_BOY_ENCOUNTER         ; champion
	db MUSIC_BOY_ENCOUNTER         ; brock
	db MUSIC_GIRL_ENCOUNTER        ; misty
	db MUSIC_BOY_ENCOUNTER         ; lt_surge
	db MUSIC_BAD_GUY_ENCOUNTER     ; scientist
	db MUSIC_BOY_ENCOUNTER         ; erika
	db MUSIC_BOY_ENCOUNTER         ; youngster
	db MUSIC_BOY_ENCOUNTER         ; schoolboy
	db MUSIC_BOY_ENCOUNTER         ; bird_keeper
	db MUSIC_GIRL_ENCOUNTER        ; lass
	db MUSIC_GIRL_ENCOUNTER        ; janine
	db MUSIC_BAD_GUY_ENCOUNTER     ; cooltrainerm
	db MUSIC_GIRL_ENCOUNTER        ; cooltrainerf
	db MUSIC_GIRL_ENCOUNTER        ; beauty
	db MUSIC_BAD_GUY_ENCOUNTER     ; pokemaniac
	db MUSIC_BAD_GUY_ENCOUNTER     ; gruntm
	db MUSIC_BAD_GUY_ENCOUNTER     ; gentleman
	db MUSIC_GIRL_ENCOUNTER        ; skier
	db MUSIC_GIRL_ENCOUNTER        ; teacher
	db MUSIC_GIRL_ENCOUNTER        ; sabrina
	db MUSIC_BOY_ENCOUNTER         ; bug_catcher
	db MUSIC_BAD_GUY_ENCOUNTER     ; fisher
	db MUSIC_BAD_GUY_ENCOUNTER     ; swimmerm
	db MUSIC_GIRL_ENCOUNTER        ; swimmerf
	db MUSIC_BAD_GUY_ENCOUNTER     ; sailor
	db MUSIC_BAD_GUY_ENCOUNTER     ; super_nerd
	db MUSIC_RIVAL_ENCOUNTER       ; rival2
	db MUSIC_BAD_GUY_ENCOUNTER     ; guitarist
	db MUSIC_BAD_GUY_ENCOUNTER     ; hiker
	db MUSIC_BAD_GUY_ENCOUNTER     ; biker
	db MUSIC_BOY_ENCOUNTER         ; blaine
	db MUSIC_BAD_GUY_ENCOUNTER     ; burglar
	db MUSIC_BAD_GUY_ENCOUNTER     ; firebreather
	db MUSIC_BAD_GUY_ENCOUNTER     ; juggler
	db MUSIC_BAD_GUY_ENCOUNTER     ; blackbelt_t
	db MUSIC_BAD_GUY_ENCOUNTER     ; executivem
	db MUSIC_BOY_ENCOUNTER         ; psychic_t
	db MUSIC_GIRL_ENCOUNTER        ; picnicker
	db MUSIC_BOY_ENCOUNTER         ; camper
	db MUSIC_BAD_GUY_ENCOUNTER     ; executivef
	db MUSIC_BAD_GUY_ENCOUNTER     ; sage
	db MUSIC_BOY_ENCOUNTER         ; medium
	db MUSIC_BAD_GUY_ENCOUNTER     ; boarder
	db MUSIC_BAD_GUY_ENCOUNTER     ; pokefanm
	db MUSIC_GIRL_ENCOUNTER        ; kimono_girl
	db MUSIC_GIRL_ENCOUNTER        ; twins
	db MUSIC_GIRL_ENCOUNTER        ; pokefanf
	db MUSIC_BAD_GUY_ENCOUNTER     ; red
	db MUSIC_RIVAL_ENCOUNTER       ; blue
	db MUSIC_BAD_GUY_ENCOUNTER     ; officer
	db MUSIC_BAD_GUY_ENCOUNTER     ; gruntf
	assert_table_length NUM_TRAINER_CLASSES + 1
	db MUSIC_BAD_GUY_ENCOUNTER     ; unused
	db MUSIC_BAD_GUY_ENCOUNTER     ; unused
	db MUSIC_BAD_GUY_ENCOUNTER     ; unused
	db MUSIC_BAD_GUY_ENCOUNTER     ; unused
