SongNames:
    db  "NOTHING             "
    db  "                    "
    db  "Title Screen (RBY)  "
    db  "                    "
    db  "Route 1 (RBY)       "
    db  "                    "
    db  "Route 3 (RBY)       "
    db  "                    "
    db  "Route 11 (RBY)      "
    db  "                    "
    db  "Pokemon Channel /   "
    db  "Magnet Train        "
    db  "VS. Gym Leader (RBY)"
    db  "                    "
    db  "VS. Trainer (RBY)   "
    db  "                    "
    db  "VS. Wild Pokemon    "
    db  "(RBY)               "
    db  "Pokemon Center (RBY)"
    db  "                    "
    db  "! Bad Trainer (RBY) "
    db  "                    "
    db  "! Girl Trainer (RBY)"
    db  "                    "
    db  "! Boy Trainer (RBY) "
    db  "                    "
    db  "Heal Pokemon (RBY)  "
    db  "                    "
    db  "Lavender Town (Gen 2"
    db  "Melody)             "
    db  "Viridian Forest     "
    db  "(RBY)               "
    db  "Mt. Moon (RBY)      "
    db  "                    "
    db  "Guidepost (RBY)     "
    db  "                    "
    db  "Game Corner (RBY)   "
    db  "                    "
    db  "Bike (GSC)          "
    db  "                    "
    db  "Hall of Fame (RBY)  "
    db  "                    "
    db  "Viridian City (RBY) "
    db  "                    "
    db  "Celadon City (RBY)  "
    db  "                    "
    db  "Defeated Trainer    "
    db  "(RBY)               "
    db  "Defeated Wild       "
    db  "Pokemon (RBY)       "
    db  "Defeated Gym Leader "
    db  "(RBY)               "
    db  "Mt. Moon Square     "
    db  "(GSC)               "
    db  "Gym (RBY)           "
    db  "                    "
    db  "Pallet Town (RBY)   "
    db  "                    "
    db  "Professor Oak's Lab "
    db  "(RBY)               "
    db  "Professor Oak       "
    db  "Arrives (RBY)       "
    db  "Rival Blue / Silver "
    db  "Arrives (RBY)       "
    db  "Rival Blue / Silver "
    db  "Leaves (RBY)        "
    db  "Johto Surf          "
    db  "                    "
    db  "Evolution / Safari  "
    db  "Zone (RBY)          "
    db  "Intro Speech (RBY)  "
    db  "(National Park)     "
    db  "Credits (Gen 2      "
    db  "Melody)             "
    db  "Azalea Town         "
    db  "                    "
    db  "Cherrygrove City    "
    db  "                    "
    db  "VS. Blue (RBY)      "
    db  "(Kimono Girl)       "
    db  "Ruins of Alph (GSC) "
    db  "                    "
    db  "VS. Wild Johto      "
    db  "Pokemon (GSC)       "
    db  "VS. Johto Trainer   "
    db  "(GSC)               "
    db  "Route 30 (GSC)      "
    db  "                    "
    db  "Ecruteak City       "
    db  "                    "
    db  "Violet City         "
    db  "                    "
    db  "VS. Johto Gyn Leader"
    db  "(GSC)               "
    db  "VS. Red (GSC)       "
    db  "                    "
    db  "Cerulean City (RBY) "
    db  "(VS. Rival)         "
    db  "Cinnabar Island     "
    db  "(RBY)(VS. Rocket)   "
    db  "Professor Elm's Lab "
    db  "                    "
    db  "Lavender Town (RBY) "
    db  "(Dark Cave)         "
    db  "Route 29 (GSC)      "
    db  "                    "
    db  "Route 34            "
    db  "                    "
    db  "SS Anne (RBY) (SS   "
    db  "Aqua)               "
    db  "Trade (RBY) (!      "
    db  "Youth)              "
    db  "Trade (RBY) (!      "
    db  "Woman)              "
    db  "Rival Blue Arrives  "
    db  "-R22-(RBY)(! Rocket)"
    db  "Rival Blue Leaves   "
    db  "-R22-(RBY)(! Maniac)"
    db  "Cinnabar Mansion    "
    db  "(RBY)(! Sage)       "
    db  "New Bark Town /     "
    db  "Silent Hills        "
    db  "Goldenrod City      "
    db  "                    "
    db  "Vermilion City (RBY)"
    db  "                    "
    db  "Viridian City (HOF) "
    db  "(RBY)(PokeChannel)  "
    db  "PokeFlute Channel   "
    db  "(GSC)               "
    db  "Tin Tower (GSC)     "
    db  "                    "
    db  "Sprout Tower (GSC)  "
    db  "                    "
    db  "Burned Tower (GSC)  "
    db  "                    "
    db  "Lighthouse (GSC)    "
    db  "                    "
    db  "Route 42            "
    db  "                    "
    db  "Pokemon League (RBY)"
    db  "                    "
    db  "Route 37 (GSC)      "
    db  "                    "
    db  "Rocket Hideout (RBY)"
    db  "                    "
    db  "Dragons' Den (GSC)  "
    db  "                    "
    db  "VS. Wild Johto      "
    db  "Pokemon (Night)(GSC)"
    db  "Unown Signal (GSC)  "
    db  "                    "
    db  "Successful Capture  "
    db  "(RBY)               "
    db  "Route 26            "
    db  "                    "
    db  "Starman (Yoshi)(Mom)"
    db  "                    "
    db  "Pokemon Tower (RBY) "
    db  "(Victory Road)      "
    db  "Pokemon Lullaby     "
    db  "(GSC)               "
    db  "Surf (RBY) (Pokemon "
    db  "March)              "
    db  "Opening Movie       "
    db  "(Light)(GSC)        "
    db  "Opening Movie (RBY) "
    db  "                    "
    db  "Jigglypuff's Song   "
    db  "(RBY)(Main Menu)    "
    db  "Ruins of Alph       "
    db  "Interior (GSC)      "
    db  "Silph Co. (RBY)(Team"
    db  "Rocket Overture)    "
    db  "Credits (RBY)(Dance "
    db  "Theater)            "
    db  "VS. Menu (Yoshi)(Bug"
    db  "Contest Results)    "
    db  "Bike (RBY)          "
    db  "                    "
    db  "Rocket Signal (GSC) "
    db  "                    "
    db  "Printer (YGSC)      "
    db  "                    "
    db  "THE END (GSC)       "
    db  "                    "
