; See song sections in audio.asm.

Music:
; entries correspond to MUSIC_* constants
	dba Music_Nothing
	dba Music_TitleScreen
	dba Music_Routes1
	dba Music_Routes3
	dba Music_Routes4
	dba Music_PokeChannel
	dba Music_GymLeaderBattle
	dba Music_TrainerBattle
	dba Music_WildBattle
	dba Music_Pokecenter
	dba Music_MeetEvilTrainer
	dba Music_MeetFemaleTrainer
	dba Music_MeetMaleTrainer
	dba Music_HealPokemon
	dba Music_LavenderTownHappy
	dba Music_Dungeon2
	dba Music_Dungeon3
	dba Music_MuseumGuy
	dba Music_GameCorner
	dba Music_Bicycle
	dba Music_HallOfFame
	dba Music_Cities1
	dba Music_Celadon
	dba Music_DefeatedTrainer
	dba Music_DefeatedWildMon
	dba Music_DefeatedGymLeader
	dba Music_MtMoonSquare
	dba Music_Gym
	dba Music_PalletTown
	dba Music_OaksLab
	dba Music_MeetProfOak
	dba Music_MeetRival
	dba Music_MeetRival_AlternateStart
	dba Music_Surf
	dba Music_SafariZone
	dba Music_Routes2
	dba Music_CreditsGSC
	dba Music_AzaleaTown
	dba Music_CherrygroveCity
	dba Music_FinalBattle
	dba Music_RuinsOfAlph
	dba Music_JohtoWildBattle
	dba Music_JohtoTrainerBattle
	dba Music_Route30
	dba Music_EcruteakCity
	dba Music_VioletCity
	dba Music_JohtoGymBattle
	dba Music_ChampionBattle
	dba Music_Cities2
	dba Music_Cinnabar
	dba Music_ElmsLab
	dba Music_Lavender
	dba Music_Route29
	dba Music_Route34
	dba Music_SSAnne
	dba Music_Trade1
	dba Music_Trade2
	dba Music_MeetRival_AlternateTempo
	dba Music_MeetRival_AlternateStartAndTempo
	dba Music_CinnabarMansion
	dba Music_SilentHills
	dba Music_GoldenrodCity
	dba Music_Vermilion
	dba Music_Cities1_AlternateTempo
	dba Music_PokeFluteChannel
	dba Music_TinTower
	dba Music_SproutTower
	dba Music_BurnedTower
	dba Music_Lighthouse
	dba Music_LakeOfRage
	dba Music_IndigoPlateau
	dba Music_Route37
	dba Music_Dungeon1
	dba Music_DragonsDen
	dba Music_JohtoWildBattleNight
	dba Music_UnownSignal
	dba Music_CaughtWildMon
	dba Music_Route26
	dba Music_Starman
	dba Music_PokemonTower
	dba Music_PokemonLullaby
	dba Music_Surfing
	dba Music_GoldSilverOpening
	dba Music_IntroBattle
	dba Music_JigglypuffSong
	dba Music_AlphInterior
	dba Music_SilphCo
	dba Music_Credits
	dba Music_VSMenu1
	dba Music_BikeRiding
	dba Music_RocketSignal
	dba Music_Printer
	dba Music_PostCredits
